#ifndef SNCF_CITIES_H
#define SNCF_CITIES_H

char * sncf_cities[] = {
	"Aachen (DE)",
	"Abbeville (FR)",
	"Agde (FR)",
	"Agen (FR)",
	"Aix-en-Provence TGV (FR)",
	"Aix-en-Provence centre (FR)",
	"Aime la Plagne (FR)",
	"Aix-les-Bains (FR)",
	"Aigle (CH)",
	"Albertville (FR)",
	"Alès (FR)",
	"Alençon (FR)",
	"Albi Ville (FR)",
	"Alassio (IT)",
	"Amsterdam (NL)",
	"Amsterdam Central Station (NL)",
	"Amsterdam Zuid (NL)",
	"Amsterdam Airport (Schiphol - NL)",
	"Amiens (FR)",
	"Amboise (FR)",
	"Amersfoort (NL)",
	"Ancona (IT)",
	"Angers (FR)",
	"Angoulême (FR)",
	"Annecy (FR)",
	"Antwerp (BE)",
	"Antibes (FR)",
	"Annemasse (FR)",
	"Ancenis (FR)",
	"Arles (FR)",
	"Arras (FR)",
	"Arcachon (FR)",
	"Argelès-sur-mer (FR)",
	"Argentan (FR)",
	"Arnhem (NL)",
	"Argenton-Sur-Creuse (FR)",
	"Arlon (BE)",
	"Arezzo (IT)",
	"Ashford (GB)",
	"Auray (FR)",
	"Augsburg (DE)",
	"Auxerre (FR)",
	"Aurillac (FR)",
	"Aulnoye - Aymeries (FR)",
	"Avignon TGV (FR)",
	"Avignon Centre (FR)",
	"Ax-Les-Thermes (FR)",
	"Basel (CH)",
	"Barcelona (ES)",
	"Bayonne (FR)",
	"Bayeux (FR)",
	"Baden (CH)",
	"Bandol (FR)",
	"Bardonecchia (IT)",
	"Banyuls-Sur-Mer (FR)",
	"Bar-le-duc (FR)",
	"Berne (CH)",
	"Besançon (FR)",
	"Beaune (FR)",
	"Berlin Hbf (DE)",
	"Bergerac (FR)",
	"Beauvais (FR)",
	"Belfort (FR)",
	"Berchem (6km from Antwerp - BE)",
	"Berlin Spandau (DE)",
	"Berlin Suedkreuz (DE)",
	"Bernay (FR)",
	"Bettembourg (LU)",
	"Berlin Ostbf( DE)",
	"Bellegarde-sur-Valserine (FR)",
	"Béziers (FR)",
	"Béthune (FR)",
	"Biarritz (FR)",
	"Bienne (CH)",
	"Bielefeld (DE)",
	"Blois (FR)",
	"Bordeaux (FR)",
	"Bourg-Saint-Maurice (funicular to 'Les Arcs' ski resort - FR)",
	"Bourges (FR)",
	"Bologne (FR)",
	"Bologna (IT)",
	"Bourg-en-Bresse (FR)",
	"Boulogne-sur-mer (FR)",
	"Bonn (DE)",
	"Bourgoin-Jallieu (FR)",
	"Bochum (DE)",
	"Brussels Midi (BE)",
	"Brussels National Airport (BE)",
	"Brussels Nord (BE)",
	"Brussels Luxembourg (BE)",
	"Bruges (BE)",
	"Brest (FR)",
	"Brive-la-Gaillarde (FR)",
	"Briançon (FR)",
	"Brescia (IT)",
	"Brigue (CH)",
	"Breda (NL)",
	"Bremen (DE)",
	"Brno (CS)",
	"Budapest (HU)",
	"Burgos (ES)",
	"Busigny (FR)",
	"Bühl (DE)",
	"Cannes (FR)",
	"Caen (FR)",
	"Carcassonne (FR)",
	"Calais (all stations - FR)",
	"Calais-Frethun - TGV and Eurostar station (FR)",
	"Cahors (FR)",
	"Calais Ville (FR)",
	"Castelnaudary (FR)",
	"Cambrai (FR)",
	"Capdenac (FR)",
	"Carmaux (FR)",
	"Cerbère (FR)",
	"Chambéry (FR)",
	"Champagne-Ardenne TGV (8km from Reims - FR)",
	"Chamonix (FR)",
	"Châteauroux (FR)",
	"Chartres (FR)",
	"Cherbourg (FR)",
	"Chalon-sur-Saône (FR)",
	"Charleroi (BE)",
	"Châtellerault (FR)",
	"Cholet (FR)",
	"Charleville-Mézières (FR)",
	"Chaumont (FR)",
	"Châlons-en-Champagne (FR)",
	"Chiasso (CH)",
	"Clermont-Ferrand (FR)",
	"Cluses (FR)",
	"Cologne Hbf (DE)",
	"Colmar (FR)",
	"Cognac (FR)",
	"Collioure (FR)",
	"Compiègne (FR)",
	"Copenhague (DK)",
	"Coblence (DE)",
	"Cologne Deutz (DE)",
	"Cracow (PL)",
	"Creil (FR)",
	"Croix - Wasquehal (FR)",
	"Culoz (FR)",
	"Culmont - Chalindrey (FR)",
	"Dax (FR)",
	"Darmstadt (DE)",
	"Delft (NL)",
	"Disneyland Paris (Marne-la-Vallée Chessy - FR)",
	"Dijon (FR)",
	"Dieppe (FR)",
	"Die (FR)",
	"Dol-de-Bretagne (FR)",
	"Donaueschingen (DE)",
	"Dole (FR)",
	"Douai (FR)",
	"Dortmund (DE)",
	"Dordrecht (NL)",
	"Dresden (DE)",
	"Dunkerque (FR)",
	"Duisburg (DE)",
	"Düsseldorf Hbf (DE)",
	"Düsseldorf Airport (DE)",
	"Ebbsfleet International (GB)",
	"Ecole-Valentin (FR)",
	"Eindhoven (NL)",
	"Eisenach (DE)",
	"Embrun (FR)",
	"Enschede (NL)",
	"Epernay (FR)",
	"Epinal (FR)",
	"Essen (DE)",
	"Essen (BE)",
	"Etaples - Le Touquet (FR)",
	"Eu (FR)",
	"Evreux (FR)",
	"Evian-les-bains (FR)",
	"Facture - Biganos (FR)",
	"Figueres (ES)",
	"Florence (IT)",
	"Florence Rifredi (IT)",
	"Florence Campo Di Marte (IT)",
	"Florence Santa Maria Novella (IT)",
	"Forbach (FR)",
	"Foix (FR)",
	"Fontainebleau-Avon (FR)",
	"Frankfurt (DE)",
	"Frasne (FR)",
	"Fribourg (CH)",
	"Freiburg Im Breisgau (DE)",
	"Frankfurt Airport (DE)",
	"Fréjus (FR)",
	"Futuroscope - TGV station (11km from Poitiers - FR)",
	"Gap (FR)",
	"Geneva (CH)",
	"Geneva Airport (CH)",
	"Genoa (IT)",
	"Genolhac (FR)",
	"Ghent (BE)",
	"Girona (ES)",
	"Gien (FR)",
	"Gourdon (FR)",
	"Goeppingen (DE)",
	"Grenoble (FR)",
	"Granville (FR)",
	"Granada (ES)",
	"Gstaad (CH)",
	"Guingamp (FR)",
	"Guéret (FR)",
	"Hannover (DE)",
	"Hamburg Hbf (DE)",
	"Hazebrouck (FR)",
	"Hasselt (BE)",
	"Hamburg Altona (DE)",
	"Hagen (DE)",
	"Haarlem (NL)",
	"Hendaye (FR)",
	"Hendaye beach (FR)",
	"Heidelberg (DE)",
	"Hirson (FR)",
	"Homburg (DE)",
	"Hyères (FR)",
	"Interlaken (CH)",
	"Interlaken West (CH)",
	"Innsbruck (AT)",
	"Interlaken Ost (CH)",
	"Irun (ES)",
	"Issoudun (FR)",
	"Juan-les-pins (FR)",
	"Juvisy (FR)",
	"Karlsruhe (DE)",
	"Kaiserslautern (DE)",
	"Kassel (DE)",
	"Kehl (DE)",
	"Kiel (DE)",
	"Kortrijk (BE)",
	"Kutno (PL)",
	"L'Hospitalet-Près-L'Andorre (FR)",
	"L'Argentière-Les-Écrins (FR)",
	"Lausanne (CH)",
	"La Rochelle (FR)",
	"Laval (FR)",
	"La Baule Escoublac (FR)",
	"La Roche-sur-Yon (FR)",
	"Lamballe (FR)",
	"Lannion (FR)",
	"La Souterraine (FR)",
	"Landry (FR)",
	"Latour-De-Carol (FR)",
	"Laroche - Migennes  (FR)",
	"La Charité sur Loire (FR)",
	"Lannemezan (FR)",
	"Landerneau (FR)",
	"La Chaux de Fonds (CH)",
	"La Teste (FR)",
	"Lauterbourg (FR)",
	"Le Mans (FR)",
	"Le Creusot Montceau Mo TGV (FR)",
	"Les Arcs Draguignan (FR)",
	"Le Havre (FR)",
	"Le Puy-en-Velay (FR)",
	"Les Sables d'Olonne (FR)",
	"Les Aubrais (4km from Orleans town centre - FR)",
	"Le Croisic (FR)",
	"Leuven (BE)",
	"Leiden (NL)",
	"Lens (FR)",
	"Le Pouliguen (FR)",
	"Leukerbad (CH)",
	"Lille Flandres - TGV station (FR)",
	"Lille (all stations - FR)",
	"Lille Europe - TGV and Eurostar station (FR)",
	"Liège (BE)",
	"Limoges (FR)",
	"Libourne (FR)",
	"Lisieux (FR)",
	"Linz (AT)",
	"London St. Pancras (GB)",
	"Lourdes (FR)",
	"Lorraine TGV (35km from Metz and Nancy - FR)",
	"Lorient (FR)",
	"Lons-le-Saunier (FR)",
	"Longwy (FR)",
	"Loèche (CH)",
	"Luxemburg (LU)",
	"Luchon (FR)",
	"Lunéville (FR)",
	"Lyon Part Dieu (FR)",
	"Lyon (all stations - FR)",
	"Lyon Perrache (FR)",
	"Lyon Saint Exupery Airport - TGV station (FR)",
	"Marseille (FR)",
	"Massy - TGV station (24km from Paris - FR)",
	"Magdeburg (DE)",
	"Maastricht (NL)",
	"Martigny (CH)",
	"Marmande (FR)",
	"Mainz (DE)",
	"Mandelieu (FR)",
	"Massy Palaiseau (FR)",
	"Mannheim (DE)",
	"Madrid (ES)",
	"Mantes-La-Jolie (FR)",
	"Mâcon (all stations - FR)",
	"Mâcon Loché TGV (FR)",
	"Mâcon centre (FR)",
	"Metz Centre (FR)",
	"Menton (FR)",
	"Meuse TGV (FR)",
	"Mechelen (BE)",
	"Metz Nord (FR)",
	"Melun (FR)",
	"Milan (all stations - IT)",
	"Milan Garibaldi (IT)",
	"Milan Rogoredo (IT)",
	"Milan Central station (IT)",
	"Miramas (FR)",
	"Montgenèvre",
	"Montpellier (FR)",
	"Mont-Saint-Michel (FR)",
	"Moutiers - Salins - Brides-les-Bains (FR)",
	"Montélimar (FR)",
	"Monaco - Monte-Carlo (FR)",
	"Morlaix (FR)",
	"Modane (FR)",
	"Moulins-sur-Allier (FR)",
	"Montbard (FR)",
	"Mons (BE)",
	"Montdauphin Guillestre (FR)",
	"Montauban (FR)",
	"Montluçon (FR)",
	"Montreux (CH)",
	"Mont de Marsan (FR)",
	"Mouchard (FR)",
	"Montbéliard (FR)",
	"Morcenx (FR)",
	"Morges (CH)",
	"Mouscron (BE)",
	"Montréjeau Gourdan-Poulignan (FR)",
	"Montargis (FR)",
	"Montauban de Bretagne (FR)",
	"Moscow Iaroslavsk (RU)",
	"Moscow Kievskaia (RU)",
	"Moscow Kurskaia (RU)",
	"Moscow Belorusskaia (RU)",
	"Moscow Oktiabrskaia (RU)",
	"Munich Hbf (DE)",
	"Mulhouse (FR)",
	"Munster (FR)",
	"Mussidan (FR)",
	"Mühlacker (DE)",
	"Nijnii Novgorod (RU)",
	"Nantes (FR)",
	"Narbonne (FR)",
	"Nancy (FR)",
	"Namur (BE)",
	"Naples (IT)",
	"Neuchatel (CH)",
	"Nevers (FR)",
	"Neustadt (DE)",
	"Nice (FR)",
	"Niort (FR)",
	"Nivelles (BE)",
	"Nîmes (FR)",
	"Novara (IT)",
	"Nuremberg (DE)",
	"Nyon (CH)",
	"Offenbourg (DE)",
	"Ollioules (5km from Sanary-sur-mer - FR)",
	"Olten (CH)",
	"Orléans centre (FR)",
	"Orange (FR)",
	"Orthez (FR)",
	"Ostend (BE)",
	"Osnabrück (DE)",
	"Ottignies (BE)",
	"Oulx-Cesana-Clavière-Sestrières (IT)",
	"Paris (all stations - FR)",
	"Paris Marne-la-Vallée Chessy (200m from Disneyland Paris - TGV and Ouigo station - FR)",
	"Paris Roissy Charles de Gaulle Airport (TGV station - CDG 2 - 25km from Paris - FR)",
	"Pau (FR)",
	"Paimpol (FR)",
	"Padua (IT)",
	"Parma (IT)",
	"Perpignan (FR)",
	"Perugia (IT)",
	"Périgueux (FR)",
	"Pfaeffikon (CH)",
	"Piacenza (IT)",
	"Plouaret-Tregor (FR)",
	"Poitiers centre (FR)",
	"Portbou (ES)",
	"Pontorson (10km from Mont-Saint-Michel - FR)",
	"Pornichet (FR)",
	"Pontarlier (FR)",
	"Pont  l'Evêque (FR)",
	"Prague (CS)",
	"Quimper (FR)",
	"Quiberon (FR)",
	"Quimperle (FR)",
	"Rennes (FR)",
	"Reims (FR)",
	"Redon (FR)",
	"Reggio Emilia AV (high-speed trains - IT)",
	"Reggio Emilia (City centre - IT)",
	"Remiremont (FR)",
	"Rethel (FR)",
	"Reutlingen (DE)",
	"Riom Châtelguyon (FR)",
	"Rimini (IT)",
	"Rimini (city center - IT)",
	"Rotterdam (NL)",
	"Rome (IT)",
	"Rome Tiburtina (IT)",
	"Rome Ostiense (IT)",
	"Rome Termini SP	(IT)",
	"Rouen (FR)",
	"Royan (FR)",
	"Roanne (FR)",
	"Roosendaal (NL)",
	"Rosporden (FR)",
	"Roscoff (FR)",
	"Rochefort (FR)",
	"Rodez (FR)",
	"Roubaix (FR)",
	"Ruffec (FR)",
	"Saint-Pierre-des-Corps (à 4km de Tours) (FR)",
	"Saint-Malo (FR)",
	"Saint-Raphaël (FR)",
	"Sarrebrück (DE)",
	"Smolensk (RU)",
	"St Petersburg Glavny (RU)",
	"Saint Brieuc (FR)",
	"Saint Etienne (all stations - FR)",
	"Saint Etienne chateaucreux (FR)",
	"Saint-Genis-Pouilly (FR)",
	"Saint-Nazaire (FR)",
	"Saumur (FR)",
	"Saint-Jean-de-Maurienne (FR)",
	"Saint-Pierre-Quiberon (FR)",
	"Saint-Jean-de-Luz (FR)",
	"Saintes (FR)",
	"Saint-Gervais-les-Bains (FR)",
	"Saint-Michel-Valloire (FR)",
	"Salzburg (AT)",
	"Sablé (FR)",
	"Saint-Quentin (FR)",
	"Sallanches Combloux Megève (FR)",
	"Saint Gilles Croix de Vie (FR)",
	"Saint-Omer (FR)",
	"San remo (IT)",
	"Savenay (FR)",
	"Saint-Dié-Des-Vosges (FR)",
	"Saint Maixent Deux Sèvres (FR)",
	"Saverne (FR)",
	"Saint-Avre-La-Chambre (FR)",
	"Saint-Gaudens (FR)",
	"Saint Gallen (CH)",
	"Sarrebourg (FR)",
	"Salamanca (ES)",
	"Saint-Germain-Des-Fossés (FR)",
	"Saint Etienne carnot (FR)",
	"Saint Moritz (CH)",
	"Seville (ES)",
	"Sens (FR)",
	"Sélestat (FR)",
	"Sète (FR)",
	"Sion (CH)",
	"Sierre (CH)",
	"Souillac (FR)",
	"Strasbourg (FR)",
	"Stuttgart (DE)",
	"Surgères (FR)",
	"Salerno (IT)",
	"Tarbes (FR)",
	"TGV Haute Picardie (FR)",
	"The Hague (NL)",
	"Thionville (FR)",
	"Thonon-les-bains (FR)",
	"Tilburg (NL)",
	"Toulouse (all stations - FR)",
	"Toulouse Matabiau (FR)",
	"Toulon (FR)",
	"Tours centre (FR)",
	"Tourcoing (FR)",
	"Tournai (BE)",
	"Toul (FR)",
	"Trouville - Deauville (FR)",
	"Troyes (FR)",
	"Trier (DE)",
	"Turin (IT)",
	"Turin Porta Susa (IT)",
	"Turin Porta Nuova (IT)",
	"Ulm (DE)",
	"Ussel (FR)",
	"Utrecht (NL)",
	"Uzerche (FR)",
	"Valence (all stations - FR)",
	"Valence - TGV station (10km from Valence city centre - FR)",
	"Vannes (FR)",
	"Vallorbe (CH)",
	"Valence Ville (FR)",
	"Valenciennes (FR)",
	"Valognes (FR)",
	"Valencia (ES)",
	"Valladolid (ES)",
	"Venice (IT)",
	"Venice Santa Lucia (IT)",
	"Venice Mestre (IT)",
	"Verona (IT)",
	"Vernon (FR)",
	"Vendôme Villiers-sur-Loir (FR)",
	"Veynes-Devoluy (FR)",
	"Vesoul (FR)",
	"Vevey (CH)",
	"Versailles (FR)",
	"Verdun (FR)",
	"Vercelli (IT)",
	"Verviers (BE)",
	"Vintimille (IT)",
	"Vichy (FR)",
	"Vienna (AT)",
	"Vierzon (FR)",
	"Villefranche-sur-saône (FR)",
	"Vienne (FR)",
	"Vittel (FR)",
	"Vitré (FR)",
	"Vitre (FR)",
	"Vicence (IT)",
	"Vitoria (ES)",
	"Vitry-le-François (FR)",
	"Visp (CH)",
	"Viareggio (IT)",
	"Vlissingen (NL)",
	"Voghera (IT)",
	"Voiron (FR)",
	"Warsaw (PL)",
	"Wolfsburg (DE)",
	"Würzburg (DE)",
	"Yvetot (FR)",
	"Yverdon (CH)",
	"Zug (CH)",
	"Zürich Hbf (CH)",
	"Zürich Airport (CH)",
	"Airport Roissy Charles-de-Gaulle (CDG 2) - local train (FR)",
	"Airport Roissy Charles-de-Gaulle (CDG 1) - local train (FR)",
	"Ermont Eaubonne (FR)",
	"Massy Verrières (FR)",
	"Versailles-Rive-Gauche Château (FR)"};

#endif
